language: node_js
node_js:
  - "0.12"
before_install:
  - npm install -g codeclimate-test-reporter
after_script:
  - codeclimate-test-reporter < coverage/lcov.info
notifications:
  email:
    on_success: never